version: '3'
services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    ports:
    # Local port mapping for debugging
      - 7854:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  odoo:
    build: .
    environment:
      - SOMKOENV=DEV
    links:
      - db
    ports:
    # Local port mapping for development
      - 9563:8069
    volumes:
      - ./custom:/mnt/repo/custom
      - ./third:/mnt/repo/third
      - odoo-data:/var/lib/odoo

volumes:
  odoo-data:
  db-data:
